# Generated by Django 4.1.2 on 2022-10-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_resetuserpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='resetuserpassword',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default='2022-10-10'),
            preserve_default=False,
        ),
    ]
