# Generated by Django 4.1.2 on 2022-10-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_messages_options_messages_receiver_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AlterField(
            model_name='messages',
            name='files',
            field=models.FileField(blank=True, upload_to='conversation_files/'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='images',
            field=models.ImageField(blank=True, upload_to='conversation_images/'),
        ),
    ]
