# Generated by Django 4.1.2 on 2022-10-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.CharField(blank=True, default="I'm Awesome!", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Away', 'Away'), ('Offline', 'Offline')], default='Offline', max_length=15, null=True),
        ),
    ]
